### ISSUE TITLE
Compilation errors in Sentry Flutter due to Kotlin API incompatibilities [Execution failed for task ':sentry_flutter:compileReleaseKotlin'.]

### ISSUE THREAD

**Issue by Alex-esc1** [getsentry/sentry-dart#2396]
**THIS IS FIXED IN `8.10.1`**

### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1 24B83 darwin-arm64, locale ru-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.95.2)
[✓] Network resources

### Version

8.10.0

### Steps to Reproduce

e: file:///Users/alex/.pub-cache/hosted/pub.dev/sentry_flutter-8.10.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutter.kt:68:50 Unresolved reference: uppercase
e: file:///Users/alex/.pub-cache/hosted/pub.dev/sentry_flutter-8.10.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt:177:55 Unresolved reference: toDuration
e: file:///Users/alex/.pub-cache/hosted/pub.dev/sentry_flutter-8.10.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt:177:66 This declaration needs opt-in. Its usage must be marked with '@kotlin.time.ExperimentalTime' or '@OptIn(kotlin.time.ExperimentalTime::class)'
e: file:///Users/alex/.pub-cache/hosted/pub.dev/sentry_flutter-8.10.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt:177:79 This declaration needs opt-in. Its usage must be marked with '@kotlin.time.ExperimentalTime' or '@OptIn(kotlin.time.ExperimentalTime::class)'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sentry_flutter:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

### Expected Result

The assembly worked perfectly, a couple of hours ago everything broke down

### Actual Result

Build should be successful

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey, thx for the issue, I'll have a look

**Comment by buenaflor** [comment]
meanwhile you can keep the version to `8.9.0` if you need it to compile right now

**Comment by Alex-esc1** [comment]
@buenaflor I stopped working on version 8.9.0, I upgraded to 8.10.0 and it doesn't work
I tried to roll back, but now I get the error all the time

**Comment by Alex-esc1** [comment]
![Image](https://github.com/user-attachments/assets/b3454b7d-7d66-491a-9fa6-bab959f461c1)
![Image](https://github.com/user-attachments/assets/ab08c9c2-979d-41b1-928a-da21e0163737)
now it works, please make changes

**Comment by Alex-esc1** [comment]
val sentryLevel = SentryLevel.valueOf(it.toUpperCase(Locale.getDefault()))  ------- SentryFlutter.kt

  @OptIn(kotlin.time.ExperimentalTime::class)
  private fun fetchNativeAppStart(result: Result)  ------- for SentryFlutterPlugin.kt

**Comment by buenaflor** [comment]
what kotlin version do you use? interesting that this wasn't caught or errored on our side

**Comment by SamuelMTDavies** [comment]
Also experiencing this error on our production builds.

**Comment by Alex-esc1** [comment]
@buenaflor I used version 1.9.0 and version 2.0.20 (both of them had no problems, but true until today)

**Comment by buenaflor** [comment]
I will prepare a hotfix

**Comment by Alex-esc1** [comment]
@buenaflor Thank you, this is very important for all of us

**Comment by buenaflor** [comment]
`8.10.1` should be released shortly, within the next hour

**Comment by Alex-esc1** [comment]
@buenaflor Thanks for the quick fix of the problem

**Comment by buenaflor** [comment]
@Alex-esc1 release is out, can you check if it's fixed?

**Comment by Alex-esc1** [comment]
@buenaflor Yes I can. Updated to 8.10.1, everything works
