### ISSUE TITLE
8.3.0 compile  error on macos, 7.15.0 is fine

### ISSUE THREAD

**Issue by GooRingX** [getsentry/sentry-dart#2167]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

flutter 3.22.2

### Version

8.3.0

### Steps to Reproduce

It will appear every time you compile

### Expected Result

no compile error

### Actual Result

Pods/Sentry/Sources/Sentry/SentryANRTracker.m:84:35: error: receiver type 'SentryCurrentDateProvider' for instance message is a forward declaration
        NSDate *blockDeadline = [[dateProvider date] dateByAddingTimeInterval:self.timeoutInterval];
                                  ^~~~~~~~~~~~

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey which macos version are you on?

**Comment by GooRingX** [comment]
> hey which macos version are you on?

Macos:Ventura 13.6.1
Xcode:15.2(15C500b)

**Comment by buenaflor** [comment]
@brustolin do you have a clue here?

**Comment by brustolin** [comment]
> @brustolin do you have a clue here?

Not immediately. This needs investigation.

@GooRingX do you have any specific setting in your build pipeline outside the standard Flutter configuration?

**Comment by GooRingX** [comment]
No, just run: flutter build macos

**Comment by buenaflor** [comment]
can you backtrack and check at which sdk version it started failing?

**Comment by GooRingX** [comment]
7.16

**Comment by buenaflor** [comment]
have you considered upgrading your macos version? I can't reproduce it locally

**Comment by GooRingX** [comment]
I didn't consider upgrading the system because it would be very slow after the upgrade.

**Comment by vaind** [comment]
The [cocoa SDK](https://github.com/getsentry/sentry-cocoa) builds in CI with various Xcode versions (14.3, 15.2, 13.4 are some I've noticed in various builds) on macOS 13.6.7.

Over here, the Flutter SDK builds on macOS 14 with Xcode 15.0 (https://github.com/actions/runner-images/blob/macos-14-arm64/20240714.2/images/macos/macos-14-arm64-Readme.md).

So I don't think the issue is the Xcode or OS version. Firstly, could you try using the latest version of sentry_flutter (at 8.5.0)? If it still persists, maybe there's some problem in the cocoa SDK config, [similar to this SO question](https://stackoverflow.com/a/68865518/2386130)

**Comment by GooRingX** [comment]
8.5.0


macos/Pods/Sentry/Sources/Sentry/SentryTracer.m:140:78: error: property 'systemTime' cannot be found in forward class object 'SentryCurrentDateProvider'
    _startSystemTime = SentryDependencyContainer.sharedInstance.dateProvider.systemTime;
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
In file included from /Users/user/Dev/karing/macos/Pods/Sentry/Sources/Sentry/SentryTracer.m:4:
@class SentryCurrentDateProvider;
       ^

**Comment by buenaflor** [comment]
Can you reproduce the same error when you use the sentry-cocoa SDK in a non-flutter (native macos) project?

**Comment by GooRingX** [comment]
> Can you reproduce the same error when you use the sentry-cocoa SDK in a non-flutter (native macos) project?

After upgrading to Xcode 15.3, this problem no longer exists
