### ISSUE TITLE
Sentry Crash Monitor_CPP Extension

### ISSUE THREAD

**Issue by DhineshJ** [getsentry/sentry-dart#2336]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

With the latest version in flutter facing SentryCrashMonitor_CPP Extension issue

 SentryCrashMonitor_CPPException
No type named 'terminate_handler' in namespace 'std'
× No member named 'set_terminate' in
namespace 'std'
× No type named 'set_terminate' in namespace
'std'

### Version

8.9.0

### Steps to Reproduce

With latest simulator ios 18.0 , I'm facing this issue. 

1.   add the package to pub.dev
2.  Build ios using xcode, facing issue

### Expected Result

Ios has to build without any issues. 
 SentryCrashMonitor_CPPException
No type named 'terminate_handler' in namespace 'std'
× No member named 'set_terminate' in
namespace 'std'
× No type named 'set_terminate' in namespace
'std'

### Actual Result

ios faced error with exceptions

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hi are you using xcode16?

**Comment by DhineshJ** [comment]
yes, I'm using xcode 16  and simulator v18

**Comment by buenaflor** [comment]
pls run `flutter clean` to see if it helps

**Comment by DhineshJ** [comment]
Already tried that . No Luck

**Comment by buenaflor** [comment]
which flutter version are you running on?

**Comment by devinyonas** [comment]
got the same issue when build ios app. 
I'm using 
- flutter `3.24.3`
- sentry_flutter `7.20.2`

```

Running pod install...                                            125.2s
Running Xcode build...                                          
Xcode archive done.                                         65.7s
Failed to build iOS app
Semantic Issue (Xcode): No type named 'terminate_handler' in namespace 'std'
/Users/builder/clone/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:59:12

Semantic Issue (Xcode): No member named 'set_terminate' in namespace 'std'
/Users/builder/clone/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:205:46

Semantic Issue (Xcode): No type named 'set_terminate' in namespace 'std'
/Users/builder/clone/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:207:17
```

**Comment by buenaflor** [comment]
@brustolin @philipphofmann 

any idea here?

**Comment by buenaflor** [comment]
https://github.com/getsentry/sentry-react-native/issues/3883#issuecomment-2377209574

maybe this helps (replace react native specific steps with flutter)

Bottom line is you need at least Sentry Flutter `8.9.0`

**Comment by devinyonas** [comment]
@buenaflor I think it works using `Sentry Flutter 8.9.0`, but I got another package issue. 
so I reverted and downgrade to Xcode 15.3 for now, and can build as previously

**Comment by brustolin** [comment]
This was fixed in Sentry-Cocoa 8.35.0. 
So, it needs at least Sentry-Fluter 8.8.0

**Comment by buenaflor** [comment]
> but I got another package issue

related to sentry?

**Comment by devinyonas** [comment]
> > but I got another package issue
> 
> related to sentry?

It is not related to sentry,  I think the sentry issue was fixed when using `sentry_flutter: 8.9.0`
