### PR TITLE
fix: macos compilation due to cocoa SDK changes

### LINKED ISSUE #1596: `PrivateSentrySDKOnly` isn't compiling for macOS
### Description

> 2023-08-09 15:30:12.805 xcodebuild[7721:2020644] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:macOS, arch:arm64, id:00006021-000229912E47401E }
> { platform:macOS, arch:x86_64, id:00006021-000229912E47401E }
> /Users/user/Github/sentry-dart/flutter/ios/Classes/SentryFlutterPluginApple.swift:469:62: error: type 'PrivateSentrySDKOnly' has no member 'appStartMeasurement'
>         guard let appStartMeasurement = PrivateSentrySDKOnly.appStartMeasurement else {
>                                         ~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~
> @property (class, nullable, nonatomic, readonly) SentryAppStartMeasurement *appStartMeasurement;
> ^
> @property (class, nullable, nonatomic, readonly) SentryAppStartMeasurement *appStartMeasurement;
> ^
> @class SentryDebugMeta, SentryAppStartMeasurement, SentryScreenFrames, SentryOptions,
> ^
> /Users/user/Github/sentry-dart/flutter/ios/Classes/SentryFlutterPluginApple.swift:476:56: error: cannot infer contextual base in reference to member 'cold'
>         let isColdStart = appStartMeasurement.type == .cold
>                                                       ~^~~~
> warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
> /Users/user/Github/sentry-dart/flutter/example/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'FMDB' from project 'Pods')
> ** BUILD FAILED **

@brustolin @armcknight did something change for `PrivateSentrySDKOnly`? I've not found any changes but not sure why its not compiling for macOS anymore.

### PR DESCRIPTION
**Pull request by vaind**
Broken by https://github.com/getsentry/sentry-cocoa/pull/3157 (v8.9.2) because the `SentryAppStartMeasurement` is not exported anymore.

closes #1596

Note: integration test failures are unrelated: #1605 

#skip-changelog

### CODE REVIEW

**Review by brustolin — APPROVED** [review]
LGTM

File: flutter/ios/Classes/SentryFlutterPluginApple.swift [hunk 1]
```diff
@@ -466,6 +466,7 @@ public class SentryFlutterPluginApple: NSObject, FlutterPlugin {
     }
 
     private func fetchNativeAppStart(result: @escaping FlutterResult) {
+        #if os(iOS) || os(tvOS)
```
Comment (marandaneto) [inline flutter/ios/Classes/SentryFlutterPluginApple.swift:469]: @vaind @brustolin This was available on macOS as well, this change will remove the feature on Flutter-macOS, I'd rather expose `appStartMeasurement` again for macOS on the Cocoa SDK, it's ok to be a quick fix, but I'd also open issues on the Cocoa SDK to fix this and later remove these checks on the Flutter SDK as well.

Comment (vaind) [reply flutter/ios/Classes/SentryFlutterPluginApple.swift:469]: @armcknight do you want to pitch in here since you've made the changes to remove these for macOS in https://github.com/getsentry/sentry-cocoa/pull/3157 ?

Comment (marandaneto) [reply flutter/ios/Classes/SentryFlutterPluginApple.swift:469]: Or @brustolin , both work on Cocoa.

Comment (armcknight) [reply flutter/ios/Classes/SentryFlutterPluginApple.swift:469]: Oof, just saw this, sorry for the delay. Really there was no feature _functionality_ removed from Flutter-macOS, since the app start tracker did nothing on macOS: https://github.com/getsentry/sentry-cocoa/pull/3157/files#diff-d13c2b7f6a0357a11c275412ab996c4ce37cd3923403c9d287e36e8e27274470L49

I agree it's a pain that this kind of stuff is breaking stuff downstream. We need a way to test `sentry-cocoa` integration so we can avoid or be aware of future breakages.
