### ISSUE TITLE
Exceptions thrown when calling Sentry.captureException in Flutter app

### ISSUE THREAD

**Issue by GowthamanRavichandran3** [getsentry/sentry-dart#3349]
### Platform

Flutter Mobile Android, Flutter Mobile iOS

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

\[✓\] Flutter (Channel stable, 3.35.4, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) \[991ms\]<br>    • Flutter version 3.35.4 on channel stable at /Users/gowthamanravichandran/Documents/flutter sdk/flutter<br>    • Upstream repository [https://github.com/flutter/flutter.git](<https://github.com/flutter/flutter.git>)<br>    • Framework revision d693b4b9db (9 weeks ago), 2025-09-16 14:27:41 +0000<br>    • Engine revision c298091351<br>    • Dart version 3.9.2<br>    • DevTools version 2.48.0<br>    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,<br>      enable-lldb-debugging

\[!\] Android toolchain - develop for Android devices (Android SDK version 35.0.0) \[5.1s\]<br>    • Android SDK at /Users/gowthamanravichandran/Library/Android/sdk<br>    • Emulator version 36.2.11.0 (build_id 14212360) (CL:N/A)<br>    • Platform [ANDROID-36](https://linear.app/getsentry/issue/ANDROID-36/user-consent-support), build-tools 35.0.0<br>    • Java binary at: /opt/homebrew/Cellar/openjdk@17/17.0.17/libexec/openjdk.jdk/Contents/Home/bin/java<br>      This JDK is specified by the JAVA_HOME environment variable.<br>      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.<br>    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.17+0)<br>    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

\[✓\] Xcode - develop for iOS and macOS (Xcode 16.3) \[4.8s\]<br>    • Xcode at /Applications/Xcode.app/Contents/Developer<br>    • Build 16E140<br>    • CocoaPods version 1.16.2

\[✓\] Chrome - develop for the web \[27ms\]<br>    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

\[!\] Android Studio (not installed) \[26ms\]<br>    • Android Studio not found; download from [https://developer.android.com/studio/index.html](<https://developer.android.com/studio/index.html>)<br>      (or visit [https://flutter.dev/to/macos-android-setup](<https://flutter.dev/to/macos-android-setup>) for detailed instructions).

\[✓\] VS Code (version 1.105.1) \[26ms\]<br>    • VS Code at /Applications/Visual Studio Code.app/Contents<br>    • Flutter extension version 3.122.0

\[✓\] Connected device (4 available) \[9.4s\]<br>    • IPAD-31422 (mobile) • 00008103-0014504102D3001E            • ios            • iOS 26.0 23A341<br>    • iPhone 15 (mobile)       • 9F36B7AA-0183-40F3-A69F-466C1664FB98 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)<br>    • macOS (desktop)          • macos                                • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64<br>    • Chrome (web)             • chrome                               • web-javascript • Google Chrome 142.0.7444.176

\[✓\] Network resources \[807ms\]<br>    • All expected network resources are available.

! Doctor found issues in 2 categories.

### Version

9.0.0

### Steps to Reproduce

I am using the following code in my Flutter app to capture exceptions and send them to Sentry:<br>`await Sentry.captureException(exception, stackTrace: stackTrace);`

However, when this line executes, I encounter the following exceptions in my app:

1. TimeoutException after 0:00:03.000000: Future not completed
2. 429: Too Many Requests
3. HandshakeException: Connection terminated during handshake

What I Tried

1. Using try-catch block:

```
try {
  await Sentry.captureException(
    exception,
    stackTrace: stackTrace,
  );
} catch (e, sentryErrorStack) {
  debugPrint('Failed to report to Sentry: $e');
  debugPrint('Sentry error stack: $sentryErrorStack');
}
```

But the exceptions are not caught in the catch block.

2. Using catchError:

```
await Sentry.captureException(error, stackTrace: trace).catchError((e, st) {
  return const SentryId.empty();
});
```

Even with this, the exceptions are still thrown and logged in Sentry.

### Expected Result

I want to prevent these network-related exceptions (TimeoutException, 429 Too Many Requests, HandshakeException) from being logged in Sentry or at least handle them gracefully without crashing the app.

### Actual Result

The exceptions are thrown and logged in Sentry despite using try-catch and catchError.

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey do you mean that Sentry causes these exceptions and logs them?

if yes can you send a link to one of these events to my mail at giancarlo.buenaflor@sentry.io

**Comment by GowthamanRavichandran3** [comment]
> hey do you mean that Sentry causes these exceptions and logs them?
> 
> if yes can you send a link to one of these events to my mail at [giancarlo.buenaflor@sentry.io](mailto:giancarlo.buenaflor@sentry.io)

Yes, these exceptions occur when I call Sentry.captureException() in my Flutter app. It seem to be related to the network call Sentry makes to send the event (e.g., TimeoutException, 429 Too Many Requests, HandshakeException).

I’m using a self-hosted Sentry instance, so the event links are internal and not publicly accessible.

**Comment by buenaflor** [comment]
do you have stacktraces you could share?

**Comment by JesusHdez960717** [comment]
Don't kwon if its the same error but after migrating Flutter SDK to 3.38.x y get this error (it works great with older sdk):

```dart
[sentry] [error] JNI: Failed to load contexts
         Exception in Java code called through JNI: java.lang.NoSuchMethodError: no non-static method "Lio/sentry/flutter/SentryFlutterPl...
         #0      Jni.throwException (package:jni/src/jni.dart:195:5)
         #1      _check (package:jni/src/accessors.dart:17:9)
         #2      JniIdLookupResultMethods.methodID (package:jni/src/accessors.dart:88:5)
         #3      GlobalJniEnv.GetMethodID (package:jni/src/third_party/global_env_extensions.dart:220:38)
         #4      JInstanceMethodId._.<anonymous closure> (package:jni/src/jclass.dart:96:26)
         #5      using (package:ffi/src/arena.dart:127:31)
         #6      JInstanceMethodId._ (package:jni/src/jclass.dart:94:17)
         #7      JClass.instanceMethodId (package:jni/src/jclass.dart:24:30)
         #8      SentryFlutterPlugin$Companion._id_loadContextsAsBytes (package:sentry_flutter/src/native/java/binding.dart:1406:49)
         #9      SentryFlutterPlugin$Companion._id_loadContextsAsBytes (package:sentry_flutter/src/native/java/binding.dart)
         #10     SentryFlutterPlugin$Companion.loadContextsAsBytes (package:sentry_flutter/src/native/java/binding.dart:1427:32)
         #11     SentryNativeJava.loadContexts (package:sentry_flutter/src/native/java/sentry_native_java.dart:177:48)
         #12     _LoadContextsIntegrationEventProcessor.apply (package:sentry_flutter/src/integrations/load_contexts_integration.dart:118:35)
         #13     runEventProcessors (package:sentry/src/event_processor/run_event_processors.dart:25:27)
         <asynchronous suspension>
         #14     SentryClient.captureEvent (package:sentry/src/sentry_client.dart:142:21)
         <asynchronous suspension>
         #15     Hub.captureException (package:sentry/src/hub.dart:166:20)
         <asynchronous suspension>
         #16     DefaultTaskQueue.enqueue (package:sentry/src/transport/task_queue.dart:43:16)
         <asynchronous suspension>
```

I'm reporting the error in a dio interceptor like this:
```dart
dio.interceptors.add(
      InterceptorsWrapper(
        onError: (DioException e, ErrorInterceptorHandler handler) async {
          try {
            final endpoint = e.requestOptions.uri.toString();
            final requestData = e.requestOptions.data;
            final responseData = e.response?.data;

            app.reportError(
              e,
              stackTrace: StackTrace.current,
              context: {
                'endpoint': endpoint,
                'request_data': JsonEncoder.withIndent(
                  '  ',
                ).convert(requestData),
                'response_data': JsonEncoder.withIndent(
                  '  ',
                ).convert(responseData),
              },
            );
          } catch (reportError) {
            print('Error in sentry: $reportError');
          }

          return handler.next(e);
        },
      ),
    );
```

**Comment by buenaflor** [comment]
@JesusHdez960717 do you use proguard in debug builds?

**Comment by JesusHdez960717** [comment]
@buenaflor I do use it, does it affect in something??? 
And why it was working in 3.35.x?

**Comment by buenaflor** [comment]
@JesusHdez960717 this error happens  currently only in debug builds and is fixed in the next Sentry Flutter version

**Comment by JesusHdez960717** [comment]
> [@JesusHdez960717](https://github.com/JesusHdez960717) this error happens currently only in debug builds and is fixed in the next Sentry Flutter version

So its not fixed in 9.8.0 (the current one)... i just need to wait for next release then?

**Comment by JesusHdez960717** [comment]
BTW @buenaflor since you pointed me in the right direction, I just added this to ProGuard:

```
-keep class io.sentry.flutter.** { *; }
-keep class io.sentry.** { *; }
-keep class io.sentry.android.** { *; }
```

And the problem was solved.

It looks like something in the Sentry native plugin wasn’t being preserved by R8/ProGuard. Now it is, so the required methods/classes are available at runtime. Probably some reflection + AOT quirks involved — no idea, but it works now.

**Comment by buenaflor** [comment]
@JesusHdez960717 yup thats the fix, we do have the rules in place but only the apply them to release builds

the next version also applies them to debug builds as well

**Comment by GowthamanRavichandran3** [comment]
> do you have stacktraces you could share?

There is not much details in the StackTrace, just the file name.

**Comment by buenaflor** [comment]
can you share your setup config?

**Comment by GowthamanRavichandran3** [comment]
Here’s my current setup:
`
await SentryFlutter.init((SentryFlutterOptions options) {
  options.dsn = getDsnForSentry();
});
`

Additionally, I capture Flutter errors using:
`
FlutterError.onError = (FlutterErrorDetails details) async {
  await Sentry.captureException(details.exception, stackTrace: details.stack);
};
`

**Comment by buenaflor** [comment]
Not sure if this solves your issue but you don't need to override `FlutterError.onError`, we already do it automatically if you initialize the SDK

**Comment by GowthamanRavichandran3** [comment]
> Not sure if this solves your issue but you don't need to override `FlutterError.onError`, we already do it automatically if you initialize the SDK

Does initializing the SDK mean calling SentryFlutter.init()?

**Comment by buenaflor** [comment]
Yes

**Comment by GowthamanRavichandran3** [comment]
> Yes

I’m not using appRunner because I need to determine the DSN after the user logs in. Therefore, I have to use captureException to record errors; otherwise, they won’t be sent to Sentry.

**Comment by buenaflor** [comment]
I see so SentryFlutter.init is not directly executed at startup but rather later at some point once they log in?

**Comment by GowthamanRavichandran3** [comment]
Yes

**Comment by buenaflor** [comment]
Got it, in that case it might be possible that there are some odd behaviours since the SDK is optimized and built to be run as close to the startup as possible<br><br>e.g from the docs: `Configuration should happen as early as possible in your application's lifecycle.`<br><br>Ideally it's best to rethink the approach to be able to have the init call directly at startup

**Comment by GowthamanRavichandran3** [comment]
> Got it, in that case it might be possible that there are some odd behaviours since the SDK is optimized and built to be run as close to the startup as possiblee.g from the docs: `Configuration should happen as early as possible in your application's lifecycle.`Ideally it's best to rethink the approach to be able to have the init call directly at startup

I've considered that during implementation, but in my case, the DSN can only be set after the user logs in. Because of this, I can't call init at application startup.

**Comment by buenaflor** [comment]
can you provide some specific repro steps so I can try it locally as well

**Comment by GowthamanRavichandran3** [comment]
> can you provide some specific repro steps so I can try it locally as well

Unable to reproduce this locally. Do you know why onError and catchError aren’t catching the exception? I also tried using a try-catch block, but it didn’t work either.

**Comment by buenaflor** [comment]
I'm not sure, I havent encountered these errors before coming from the SDK

can you share your SentryFlutter.init config

but without repro steps it's hard to figure out this issue
