### ISSUE TITLE
Cannot use package after Flutter upgrade to 3.29

### ISSUE THREAD

**Issue by samuel-kings** [getsentry/sentry-dart#2745]
### Platform

Flutter Mobile Android

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on Microsoft Windows [Version 10.0.26100.3194], locale en-NG)
[✓] Windows Version (11 Pro 64-bit, 24H2, 2009)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.5)
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.97.2)
[✓] VS Code, 64-bit edition (version 1.97.2)
[✓] Connected device (4 available)
[✓] Network resources

### Version

8.13.2

### Steps to Reproduce

1. Upgrade Flutter to v3.29
2. Install sentry 8.13.2 to your project
3. run the project

### Expected Result

App is supposed to run fine

### Actual Result

After upgrading Flutter to v3.29, I get this error message:

```
C:\projects\Clients\map-explorer\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:94: error: cannot find symbol
      flutterEngine.getPlugins().add(new io.sentry.flutter.SentryFlutterPlugin());
                                                          ^
  symbol:   class SentryFlutterPlugin
  location: package io.sentry.flutter
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 1m 4s
Error: Gradle task assembleDevDebug failed with exit code 1
```

### Are you willing to submit a PR?

None

**Comment by kahest** [comment]
Thanks for reporting, we'll investigate shortly. Can you try using `8.13.1` and tell us if that solves the issue for you?

@denrase please take a look, possibly related to https://github.com/getsentry/sentry-dart/issues/2735#issuecomment-2678747134

**Comment by denrase** [comment]
Created a new project with Sentry `8.13.2` and it did work for me, but I do run on macOS, not windows. 

<img width="2392" alt="Image" src="https://github.com/user-attachments/assets/40f9cff1-aa29-4e53-9730-b476bf2e2926" />
<img width="2274" alt="Image" src="https://github.com/user-attachments/assets/eebea49c-3a42-4f59-bbcc-7cb2162c93f9" />

I'm also on a more recent Android Studio version 2024.2.2.

@samuel-kings Could you try to update you Android Studio, clear cached and get back to us if this changed anything. Any more info you can give us?

<img width="388" alt="Image" src="https://github.com/user-attachments/assets/3e54dc0d-a332-4758-bcdc-d1ad7240e1b3" />

**Comment by ThomasAunvik** [comment]
Had the same issue,

Did a `./gradlew clean`

Problem fixed.

**Comment by samuel-kings** [comment]
@ThomasAunvik Yes you are right. It worked after I did a Flutter clean and deleted android/.gradle
