### ISSUE TITLE
Unsymbolicated issues after upgrading from 8.14.1 to 9.3.0.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-dart#3102]
### Platform

Flutter Mobile Android

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

NA

### Version

9.3.0

### Steps to Reproduce

sentry_flutter: ^9.3.0
sentry_dart_plugin: ^3.1.1
flutter 3.32.5

SDK init:
```
Future<void> main() async {
  ImageCache().maximumSize = 100;
  FlutterForegroundTask.initCommunicationPort();
  WidgetsFlutterBinding.ensureInitialized();
  await initSpineFlutter(enableMemoryDebugging: false);

  if (kDebugMode) {
    runApp(const ExcludeSemantics(child: MyApp()));
  } else {
    await SentryFlutter.init(
      (options) {
        options.dsn ='...';
        options.tracesSampleRate = 0.25;
        options.profilesSampleRate = 0.25;
        options.attachScreenshot = true;
        options.attachViewHierarchy = true;
        options.sendDefaultPii = true;
        options.replay.sessionSampleRate = 0.25;
        options.replay.onErrorSampleRate = 0.5;
        options.environment = appFlavor;

        options.privacy.maskAllImages = false;
        options.privacy.maskAllText = false;
        options.privacy.maskAssetImages = false;

        options.beforeSend = (event, hint) {
          final errorMessage =
              event.throwable?.toString() ?? event.message?.toString() ?? '';

          // Convert to lowercase for easier matching
          final lowerMessage = errorMessage.toLowerCase();

          // Simple string contains checks - more reliable than regex
          final shouldIgnore = [...];

          // Check if any ignore pattern is found in the error message
          for (final pattern in shouldIgnore) {
            if (lowerMessage.contains(pattern)) {
              return null; // Drop the event
            }
          }

          // Also check the exception chain if available
          if (event.exceptions != null) {
            for (final exception in event.exceptions!) {
              final exceptionValue = (exception.value ?? '').toLowerCase();
              for (final pattern in shouldIgnore) {
                if (exceptionValue.contains(pattern)) {
                  return null;
                }
              }
            }
          }

          // If no patterns match, send the event
          return event;
        };

        options.ignoreErrors = [...];
      },
      appRunner: () =>
          runApp(SentryWidget(child: const ExcludeSemantics(child: MyApp()))),
    );
  }
}
```

### Expected Result

Exceptions and crashes captured by the SDK contain the `debug_meta` field to symbolicate events.

### Actual Result

Events are missing `debug_meta` and are not symbolicated. 

This issue started after updating both Flutter from 3.27.3 to 3.32.5 and Sentry Flutter SDK to 9.3.0. Reverting the update does not fix the issue.

### Are you willing to submit a PR?

No

**Comment by buenaflor** [comment]
Not sure if this is some caching issue, is this only an Android problem or also iOS?

**Comment by rodolfoBee** [comment]
The app is only distributed to Android.

**Comment by buenaflor** [comment]
@rodolfoBee how do they build the app? what is the flutter command?

I see that the `debug_meta` is not missing and the correct debug file is uploaded `libapp.so` and the debug_id is correct. however I also see that the stacktrace package points to a `base.apk` instead of a `libapp.so` that's why (I assume) the symbolicator does not apply symbolication on the stacktrace

**Comment by buenaflor** [comment]
Could you share how they run the flutter build command?

Info why debug_meta might be missing in v9 we added obfuscation checks in v9 so that the debug meta loading only happens for obfuscated apps, it seems like for some reason it failed here to successfully check that it is an obfuscated app since I don't see the `LoadDebugImages` integration in the integrations list

I'll have a look what happened

**Comment by buenaflor** [comment]
For the events like v8 not working I checked the debug files and 

**Event with NOT working symbolication**
<img width="1169" height="232" alt="Image" src="https://github.com/user-attachments/assets/0cc275d0-dd9e-4c7b-9c1f-115a8457bafe" />

**Event with working symbolication**
<img width="1169" height="279" alt="Image" src="https://github.com/user-attachments/assets/e9df17d6-db21-4408-b27f-502985d09a75" />

as you can see the .symbols file is missing in the first one where symbolication doesnt work

**Comment by buenaflor** [comment]
@rodolfoBee update: the missing debug_meta should be fixed by this PR: https://github.com/getsentry/sentry-dart/pull/3104

**Comment by buenaflor** [comment]
The fix will be released in `9.6.0`

**Comment by rodolfoBee** [comment]
Reopening the issue as new events on v9.6.0-beta1 still show a similar issue.

Adding link to event and more details in the internal ticket.

**Comment by buenaflor** [comment]
@rodolfoBee I checked their latest event with `9.6.0-beta.1` 

- the debug meta is there so that is fixed ✅ 
- the `.symbols` debug file is still not uploaded -> this is a sentry dart plugin configuration problem

can they share where they put the debug symbols in? e.g `flutter build apk --split-debug-info=their/path`

**Comment by rodolfoBee** [comment]
The command used is:
```
fvm flutter build appbundle --flavor production --split-debug-info=build/debug-info
fvm flutter pub run sentry_dart_plugin
```
From what I know plugin uploads files from recursively from the `build/` folder. The `build_path` is not set in plugin config.

**Comment by buenaflor** [comment]
I'll try to repro but judging by the config it should find it and upload it even with the default config

**Comment by buenaflor** [comment]
Can they share their full config and the logs of their sentry_dart_plugin output? perhaps with `log_level = info`

I tried it out locally with the same setup but it works fine on my end with default settings (without setting a `symbol_path`)

**Comment by IgorKhramtsov** [comment]
I think I have the same issue.
In the current `9.3.0` version, when we started to obfuscate and strip debug symbols from android builds - the stack trace became unsymbolicated. I checked the `8.14.1` version and it works fine there, the stack trace is correctly mapped to readable names.
Upon bisecting the `sentry_flutter` package's commits I was able to pinpoint the first bad commit, it's https://github.com/getsentry/sentry-dart/commit/99df9b2ea5a546db88e59551e9699f189ab7e9c6 where the `sentry-android` package was bumped. 
I also pinpointed the first bad version of `sentry-android` and it's `8.4.0`. Tried to go up, in case the issue was fixed with a newer version, but can't go above `8.13.2` due to a compilation error.

The issue is that the result of `_native.loadDebugImages` is an empty list here: https://github.com/getsentry/sentry-dart/blob/f502e516fb43298e083282e04adcff20bf04b4e7/flutter/lib/src/integrations/load_image_list_integration.dart#L43

**Comment by buenaflor** [comment]
@IgorKhramtsov try out `9.6.0` which fixes this issue, the Sentry Android version shouldn't have an effect on it. This was the culprit: https://github.com/getsentry/sentry-dart/pull/2907

**Comment by IgorKhramtsov** [comment]
UPD: Ah, I found the issue, you can disregard it. It turned out to be highly specific to our project.

Since we depend on sentry in our game - we ship libsentry.so lib alongside the game lib, and after that update - the sentry couldn't work with old native sentry lib. After deleting the outdated libsentry.so that we vendor ourselves - the issue went away.

~I tried that one more time to double check. The issue persists. Here is a link to the sentry event produced with that version: https://test-p0t.sentry.io/issues/56427890/events/16058cba8f504061841e4f9a8bca3220/~

~I have a local checkout of sentry-dart repository that I used for pinpointing the commit with this bug. Using that checkout I can confirm that the issue starts to appear after I change the version of sentry_android to 8.4.0 or higher and disappears if I lower the version. The local checkout at the moment is on a `9.0.0-alpha.2` sentry_flutter version (this version hasn't introduced yet the conditional that has been fixed in https://github.com/getsentry/sentry-dart/pull/2907)~

~_I also tried to create a minimal repro, but no luck there. The project where I can observe the issue is quite big, we have a game loaded through native library, a lot of ffi/other native communication, c++ hooks into the code so it's hard to reproduce exactly that setup. At first I thought the issue might be with how we have our projects set up with native stuff, but after finding out that the issue goes away after lowering the sentry_android version - it looks like we do not interfere with sentry to cause this issue_~

**Comment by buenaflor** [comment]
@rodolfoBee is this still an issue for the customer?

**Comment by rodolfoBee** [comment]
I haven't got an update, marking as closed for now.
