### ISSUE TITLE
`PrivateSentrySDKOnly` isn't compiling for macOS

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1596]
### Description

> 2023-08-09 15:30:12.805 xcodebuild[7721:2020644] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:macOS, arch:arm64, id:00006021-000229912E47401E }
> { platform:macOS, arch:x86_64, id:00006021-000229912E47401E }
> /Users/user/Github/sentry-dart/flutter/ios/Classes/SentryFlutterPluginApple.swift:469:62: error: type 'PrivateSentrySDKOnly' has no member 'appStartMeasurement'
>         guard let appStartMeasurement = PrivateSentrySDKOnly.appStartMeasurement else {
>                                         ~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~
> @property (class, nullable, nonatomic, readonly) SentryAppStartMeasurement *appStartMeasurement;
> ^
> @property (class, nullable, nonatomic, readonly) SentryAppStartMeasurement *appStartMeasurement;
> ^
> @class SentryDebugMeta, SentryAppStartMeasurement, SentryScreenFrames, SentryOptions,
> ^
> /Users/user/Github/sentry-dart/flutter/ios/Classes/SentryFlutterPluginApple.swift:476:56: error: cannot infer contextual base in reference to member 'cold'
>         let isColdStart = appStartMeasurement.type == .cold
>                                                       ~^~~~
> warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
> /Users/user/Github/sentry-dart/flutter/example/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'FMDB' from project 'Pods')
> ** BUILD FAILED **

@brustolin @armcknight did something change for `PrivateSentrySDKOnly`? I've not found any changes but not sure why its not compiling for macOS anymore.

**Comment by marandaneto** [comment]
@brustolin @brustolin @kahest any follow up on this?

**Comment by brustolin** [comment]
Not yet. I will investigate this today.

**Comment by vaind** [comment]
I'm actually looking into this already because I wanted the new cocoa SDK for profiling support. Stopped working with cocoa v8.9.4

**Comment by vaind** [comment]
Actually, it's since v8.9.2 and this PR specifically https://github.com/getsentry/sentry-cocoa/pull/3157

seems like the SentryAppStartMeasurement is only exposed when building for iOS.
