### ISSUE TITLE
Android reporting errors but app runs just fine

### ISSUE THREAD

**Issue by zuboje** [getsentry/sentry-dart#917]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Version 10.0.22000.739], locale en-US)
    • Flutter version 3.0.3 at C:\Users\user\source\repos\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (10 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (1 available)
    • G80 (mobile) • 1080308020406374 • android-arm64 • Android 9 (API 28)

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

The version of the SDK (See pubspec.lock):
**sdk: ">=2.16.2 <3.0.0"**

---
I have the following issue:

After upgrading the package to 6.6.0 I have no problems with the application, everything works fine, but I see events in the sentry "Issues" tab. I see the following error generated:

```
java.lang.NoClassDefFoundError: io.sentry.flutter.SentryFlutterPlugin$$ExternalSyntheticLambda4
    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
    at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5421)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
``` 

**Steps to reproduce:**
I am not sure, opening the app? I do not see this in debug mode. From what I've seen this happens on Android only. Here is from the issue itself:
![image](https://user-images.githubusercontent.com/5181730/176990520-4feec117-0a82-4861-b24d-c1cbb8c3d8d5.png)

**Actual result:**
- Generating issue in sentry

**Expected result:**
- Should not be generating issues since the app is working

**Comment by marandaneto** [comment]
Dup https://github.com/getsentry/sentry-dart/issues/916
